# Generated by Django 5.2.15 on 2026-06-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
    ]
