# Generated by Django 5.2.15 on 2026-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flowers',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
