# Generated by Django 5.2.15 on 2026-06-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_category_alter_flowers_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flowers.category'),
        ),
    ]
