# Generated by Django 5.2.15 on 2026-06-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flowers_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flowers.category', verbose_name='Категории'),
        ),
    ]
